defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: smart_event_development

test:
  <<: *defaults
  database: smart_event_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOLAB_URI'] %>
  database: smart_event
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
