// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    window.Event = (function(_super) {

      __extends(Event, _super);

      function Event() {
        return Event.__super__.constructor.apply(this, arguments);
      }

      Event.prototype.defaults = {
        _id: "000000000000000000000001",
        dateDebut: "2012-02-10T08:00:00.000Z",
        dateFin: "2012-02-10T08:44:23.372Z",
        description: "Defaults",
        emplacement: "No where",
        nom: "Name"
      };

      Event.prototype.initialize = function() {
        console.log('Event Contructor');
        return this.bind("error", function(model, error) {
          return console.log("Erreur ! : " + error);
        });
      };

      Event.prototype.getId = function() {
        return this.get('id');
      };

      Event.prototype.validate = function(attributes) {
        if (attributes.name === '') {
          return "Le nom n'est pas valide";
        }
      };

      return Event;

    })(Backbone.Model);
    return window.Events = (function(_super) {

      __extends(Events, _super);

      function Events() {
        return Events.__super__.constructor.apply(this, arguments);
      }

      Events.prototype.model = Event;

      Events.prototype.url = "/api/events/";

      Events.prototype.initialize = function() {
        return console.log("Nouvelle Collection");
      };

      return Events;

    })(Backbone.Collection);
  });

}).call(this);
