#!/usr/bin/env rake

require './api.rb'

task :routes do
  SmartEvent::API.routes.each do |route|
    route_path = route.route_path.gsub('(.:format)', '').gsub(':version', route.route_version)
      puts "\n#{route.route_method} #{route_path}"
      puts " #{route.route_description}" if route.route_description
      if route.route_params.is_a?(Hash)
        params = route.route_params.map do |name, desc|
          required = desc.is_a?(Hash) ? desc[:required] : false
          description = desc.is_a?(Hash) ? desc[:desc] : desc.to_s
          type = desc.is_a?(Hash) ? desc[:type] : desc.to_s
          [ name, required, "   * (#{type}) #{name}: #{description}" ]
        end
        puts "  parameters:"
        params.each { |p| puts p[2] }
      end
  end
end
